name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      MONGODB_URI: mongodb://localhost:27017/roomloop-test
      NEXTAUTH_SECRET: test-secret-do-not-use-in-production
      NEXTAUTH_URL: http://localhost:3000

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      # Add test script when you create tests
      - name: Verify MongoDB Connection
        run: |
          apt-get update
          apt-get install -y mongodb-clients
          mongosh --eval "db.serverStatus()" ${{ env.MONGODB_URI }}
      
      # Uncomment when you add tests
      # - name: Run tests
      #   run: npm test 